
---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create Stack
Parameters:
  NameOfService:
    Description: Tagname assosiated with this stack
    Type: String
  KeyName:
    Description: Name of existing SSH keypair
    Type: AWS::EC2::KeyPair::KeyName

  DBClass:
    Description: DB instance class
    Type: String
    Default: db.t1.micro

  Vpcname:
    Description: Name of the  Vpc
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::VPC::Id>>
  Publicsubnetname:
    Description: Name of the Subnet
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsSupport: yes
      EnableDnsHostnames: yes
      Tags:
        - key: Name
          Value: !Ref Vpcname
  Publicsubnet:
     Type: AWS::EC2::Subnet
     Properties:
       AvailabilityZone: 'us-east-2b'
       CidrBlock: 172.31.16.0/20
       VpcId: !Ref VPC
       Tags:
         - Key: Name
           Value: !Ref Publicsubnetname
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VpcInternetgatewayAttachmeent:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
       InternetGatewayId: !Ref InternetGateway
       VpcId: !Ref VPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTable

  RouteTableAssosiation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Publicsubnet
      RouteTableId: !Ref PublicRouteTable








  S3Bucket:
     Type: 'AWS::S3::Bucket'
     Properties:

        BucketName: judrinbucket
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'aws:kms'
                KMSMasterKeyID: KMS-KEY-ARN
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
        Tags:
          - Key: name
            Value: !Ref NameOfService
  EC2Instance:
     Type: 'AWS::EC2::Instance'
     Properties:
        InstanceType: t2.micro
        ImageId: ami-077e31c4939f6a2f3
        InstanceInitiatedShutdownBehavior: stop
        Tags:
          - Key: Name
            Value: !Ref NameOfService
        KeyName: !Ref KeyName
        SecurityGroups:
           - default
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref DBClass



  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance


















Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
  PublicIPinstance:
    Value: !GetAtt
      - EC2Instance
      - PublicIp
  Publicsubnet:














