AWSTemplateFormatVersion: "2010-09-09"
Description: Loadbalancer
Parameters:
  Keyname:
    Description: ssh keyname
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0ff8a91507f77f867

Resources:
  AWS inastance Loadbalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Instances: !Ref AWS::Region
      Listeners:
        - InstancePort: 80
          InstanceProtocol: http






      Subnets: !Refsubnets









