---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
This stack create EC2 instance with Metadata

Parameters:

  NameOfService:
    Description: Tag name for this stack
    Type: String
  KeyName:
    Description: SSH Keyname
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be exsisting keypair
  InstanceType:
    Description: EC2 Instance Type
    Type: AWS::EC2::Instance::Id

    Default: t2.micro
  Security Group:
    Description: Security Group name
    Type: AWS::EC2::SecurityGroup::Id
    AllowedValues:
      - default
      - NONE



Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0ff8a91507f77f867


Resources:
  LNEC2 instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      SecurityGroups: !Ref Security Group

      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: object = {“a”:{“b”:{“c”:”d”}}}
                    key = a/b/c

                    object = {“x”:{“y”:{“z”:”a”}}}
                    key = x/y/z
                    value = a
  Launch Config:
    Type: AWS::EC2::LaunchTemplate
    
    Metadata:
      BlockDeviceMappings:
        - BlockDeviceMapping
      CapacityReservationSpecification:
        CapacityReservationSpecification
      CpuOptions:
        CpuOptions
      CreditSpecification:
        CreditSpecification
      DisableApiTermination: Boolean
      EbsOptimized: Boolean
      ElasticGpuSpecifications:
        - ElasticGpuSpecification
      ElasticInferenceAccelerators:
        - LaunchTemplateElasticInferenceAccelerator
      EnclaveOptions:
        EnclaveOptions
      HibernationOptions:
        HibernationOptions
      IamInstanceProfile:
        IamInstanceProfile
      ImageId: String
      InstanceInitiatedShutdownBehavior: String
      InstanceMarketOptions:
        InstanceMarketOptions
      InstanceType: String
      KernelId: String
      KeyName: String
      LicenseSpecifications:
        - LicenseSpecification
      MetadataOptions:
        MetadataOptions
      Monitoring:
        Monitoring
      NetworkInterfaces:
        - NetworkInterface
      Placement:
        Placement
      RamDiskId: String
      SecurityGroupIds:
        - String
      SecurityGroups:
        - String
      TagSpecifications:
        - TagSpecification




Outputs:






