Description: >-
This stack create EC2 instance

Parameters:
  InstanceType:

      Description: ec2 instance
      Type: AWS::EC2::Image::Id
      Default: t2.micro
      AllowedValues:
        - t2.micro
  Security Group:
    Description: SecurityGroup
    Type: String
    Default: default

  KeyName:
    Description: SSH Keyname
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be existing Keypair



Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-02e136e904f3da870


Resources:
  LNEC2 instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      SecurityGroups: !Ref Security Group

      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          wget -O ddinstall.sh https://s3.amazonaws.com/dd-agent/scripts/install_script.sh
                    export DD_API_KEY=$(aws secretsmanager get-secret-value --region eu-west-2 --secret-id ${DatadogAPIKeySecretArn} --query SecretString --output text | jq -r .DD_API_KEY)
                    export DD_SITE=datadoghq.eu
                    export DD_LOGS_ENABLED=true
                    export DD_LOGS_CONFIG_USE_HTTP=true
                    bash ./ddinstall.sh
                    export DD_AGENT_MAJOR_VERSION=7 DD_API_KEY="<DATADOG_API_KEY>" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"



  Launch Config:
    Type: AWS::EC2::LaunchTemplate

    Metadata:
      BlockDeviceMappings:
        - BlockDeviceMapping
      CapacityReservationSpecification:
        CapacityReservationSpecification
      CpuOptions:
        CpuOptions
      CreditSpecification:
        CreditSpecification
      DisableApiTermination: Boolean
      EbsOptimized: Boolean
      ElasticGpuSpecifications:
        - ElasticGpuSpecification
      ElasticInferenceAccelerators:
        - LaunchTemplateElasticInferenceAccelerator
      EnclaveOptions:
        EnclaveOptions
      HibernationOptions:
        HibernationOptions
      IamInstanceProfile:
        IamInstanceProfile
      ImageId: String
      InstanceInitiatedShutdownBehavior: String
      InstanceMarketOptions:
        InstanceMarketOptions
      InstanceType: String
      KernelId: String
      KeyName: String
      LicenseSpecifications:
        - LicenseSpecification
      MetadataOptions:
        MetadataOptions
      Monitoring:
        Monitoring
      NetworkInterfaces:
        - NetworkInterface
      Placement:
        Placement
      RamDiskId: String
      SecurityGroupIds:
        - String
      SecurityGroups:
        - String
      TagSpecifications:
        - TagSpecification


  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !GetAtt
      - LNEC2 instance
      - AvailabilityZone



  PublicIP:
    Dsescription: EC2 Instance Public IP
    Value: !GetAtt
      - LNEC2 instance
      - PublicIp
  SecurityGroup:
    Description: Security Group Name
    Value: !GetAtt
      - SecurityGroup
      - VpcId













